### ISSUE TITLE
Components not found

### ISSUE THREAD

**Issue by furkanardagul** [oghb/haxball-client#2]
Hello,

I could not find the relevant components. Is there a different way or did you forget to add it?

![Ekran Resmi 2022-11-20 18 53 45](https://user-images.githubusercontent.com/45922246/202912003-f325d2c4-72d6-4427-857e-009522e11433.png)

**Comment by oghb** [comment]
Hi, have you already read the "How to build" section in the README?

**Comment by vevampire-tr** [comment]
Yes, as you said, I read it, albeit a little late. I made the changes, then when I built without editing by default, I could not get game output on windows and macintosh (intel).

**Comment by vevampire-tr** [comment]
In addition, to give additional information, the windows build code was giving an error when building over windows, I was able to get it successfully over macintosh (intel).

**Comment by oghb** [comment]
Yes, unfortunately as I explained in the FAQs I haven't been to get the client to build with the newer versions of nativefier, hence the delay for a new update. I haven't had the time in the last few months to get back on it and see how to modify the main.ts to get it to work.

Regarding your second comment, thanks a lot: I don't have a Windows machine to test the build command on so I didn't know it wasn't working. If you get it to work please update me with the correct command!

**Comment by vevampire-tr** [comment]
As a working version, which one will I work with give the result I want?

I will forward the build code I received when I switch to windows again :)

**Comment by oghb** [comment]
I published the latest release in May, so you would need to use that version of nativefier to be able to build it (as of now)
