### ISSUE TITLE
Add a custom command

### ISSUE THREAD

**Issue by Xng70** [oghb/haxball-client#4]
Hi!
If I want to add a command to the app, something similar to unlimited extrapolation, what folder would I have to put the file in to make it work/so I can trigger it? It must be clarified that it is not a chit or anything similar to try to take advantage.

**Comment by oghb** [comment]
It depends on the command: 
- if it's something which affects the "game" – like extrapolation – you need to edit HaxBall's `game-min.js` file
- if it's something else it should be sufficient to edit the `inject-randomcode.js` file that you can find within the client folder (or .app file if you use a Mac)
 
But I can't give you any more info unless you tell me what this command would do

**Comment by Xng70** [comment]
> It depends on the command:
> 
> * if it's something which affects the "game" – like extrapolation – you need to edit HaxBall's `game-min.js` file
> * if it's something else it should be sufficient to edit the `inject-randomcode.js` file that you can find within the client folder (or .app file if you use a Mac)
> 
> But I can't give you any more info unless you tell me what this command would do

I suppose that with the indications you gave me it will work... exactly where are these folders?  I can't find them

**Comment by oghb** [comment]
The `game-min.js` is not saved within the client folder but is pulled from this repository, so if you change it you must do the same and change the link you can find at the beginning of `inject.js`.

The `inject.js` is in `resources/app/inject/`
